spring:
  application:
    name: UserServiceClient
  security:
    oauth2:
      client:
        registration:
          user-service-client-via-spring-auth-server:
            client-id: user-service-client-via-spring-auth-server
            client-secret: very-secret-code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: openid, profile
        provider:
          user-service-client-via-spring-auth-server:
            issuer-uri: http://auth.mydomain.com:8080

server:
  port: 8081
