server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          user-service-client-keycloak:
            client-id: user-service-client-keycloak
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: openid, profile
        provider:
          user-service-client-keycloak:
            issuer-uri: http://localhost:8999/realms/train-trips-realm


  config:
    import: optional:vault://
  cloud:
    vault:
      uri: ${VAULT_ADDR:}
      token: ${VAULT_TOKEN:}
      kv:
        enabled: true
        backend: secret
        default-context: db

my:
  db:
    password: ${password}