spring:
  application:
    name: TrainTripsUserService   # nazwa aplikacji
  datasource:
    url: jdbc:h2:mem:train-trips-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8050                      # port aplikacji
